import type { CakeCategoryCard, CakeProduct } from "@/types/cake";
import type { CakeOrder } from "@/types/order";

export const business = {
  name: "1001 ТОРТИ-НЕЛИ",
  address: "ул. „Гео Милев“ 5, Център, 2800 Сандански",
  shortAddress: "ул. „Гео Милев“ 5, Център, Сандански",
  phone: "074 631 001",
  tel: "074631001",
  maps: "https://maps.app.goo.gl/Sgxhn6vASGwALxJy8",
  rating: "4.6",
  reviews: "40",
};

const image = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=82`;

export const categoryCards: CakeCategoryCard[] = [
  {
    title: "Торти за рожден ден",
    description: "Елегантни, цветни и персонализирани торти за празник.",
    image: image("photo-1558301211-0d8c8ddee6ec"),
  },
  {
    title: "Детски торти",
    description: "Весели дизайни, нежни кремове и любими теми.",
    image: image("photo-1621303837174-89787a7d4729"),
  },
  {
    title: "Сватбени торти",
    description: "Изискана визия за специален ден и повече гости.",
    image: image("photo-1606890737304-57a1ca8a5b62"),
  },
  {
    title: "Шоколадови торти",
    description: "Плътни какаови вкусове, ганаш и богати пластове.",
    image: image("photo-1578985545062-69928b1d9587"),
  },
  {
    title: "Плодови торти",
    description: "Свежи плодове, леки кремове и сезонни комбинации.",
    image: image("photo-1464349095431-e9a21285b5f3"),
  },
  {
    title: "Празнични торти",
    description: "За имен ден, юбилей, фирмен повод или семейна вечер.",
    image: image("photo-1488477181946-6428a0291777"),
  },
  {
    title: "Custom торти",
    description: "Дизайн по снимка, идея, надпис и избран вкус.",
    image: image("photo-1614707267537-b85aaf00c4b7"),
  },
  {
    title: "Сладки и десерти",
    description: "Малки сладки изкушения за кафе, гости и подарък.",
    image: image("photo-1519869325930-281384150729"),
  },
];

export const products: CakeProduct[] = [
  {
    id: "berry-classic",
    name: "Класика с горски плодове",
    category: "Плодови",
    description: "Лека сметанова торта с ванилови блатове и свежи плодове.",
    portions: "8-12 порции",
    priceFrom: 48,
    image: image("photo-1565958011703-44f9829ba187"),
    tags: ["плодова", "рожден ден", "лека"],
    popular: true,
    featured: true,
    active: true,
  },
  {
    id: "choco-gold",
    name: "Шоколадово злато",
    category: "Шоколадови",
    description: "Какаови блатове, шоколадов мус и деликатен златен акцент.",
    portions: "10-14 порции",
    priceFrom: 55,
    image: image("photo-1602351447937-745cb720612f"),
    tags: ["шоколадова", "юбилей", "премиум"],
    popular: true,
    active: true,
  },
  {
    id: "kids-rainbow",
    name: "Детска дъга",
    category: "Детски",
    description: "Цветна торта с мек крем, подходяща за детско парти.",
    portions: "12-16 порции",
    priceFrom: 62,
    image: image("photo-1535141192574-5d4897c12636"),
    tags: ["детска", "рожден ден", "цветна"],
    featured: true,
    active: true,
  },
  {
    id: "wedding-cream",
    name: "Сватбена крем елеганс",
    category: "Сватбени",
    description: "Двуетажна торта с нежна декорация и вкус по избор.",
    portions: "Цена след уточнение",
    priceFrom: null,
    image: image("photo-1606890737304-57a1ca8a5b62"),
    tags: ["сватбена", "custom", "празнична"],
    active: true,
  },
  {
    id: "strawberry-dream",
    name: "Ягодова мечта",
    category: "Плодови",
    description: "Пухкави блатове, ягодов крем и плодова декорация.",
    portions: "8-10 порции",
    priceFrom: 45,
    image: image("photo-1464195244916-405fa0a82545"),
    tags: ["ягода", "лека", "плодова"],
    active: true,
  },
  {
    id: "custom-photo",
    name: "Торта по снимка",
    category: "Custom",
    description: "Персонален дизайн по снимка, тема, надпис и повод.",
    portions: "Custom",
    priceFrom: null,
    image: image("photo-1586985289688-ca3cf47d3e6e"),
    tags: ["custom", "надпис", "дизайн"],
    popular: true,
    active: true,
  },
  {
    id: "birthday-pink",
    name: "Розов празник",
    category: "Рожден ден",
    description: "Нежна торта с кремова розова визия и празничен надпис.",
    portions: "10-12 порции",
    priceFrom: 52,
    image: image("photo-1588195538326-c5b1e9f80a1b"),
    tags: ["рожден ден", "надпис", "ванилия"],
    featured: true,
    active: true,
  },
  {
    id: "festive-box",
    name: "Празнична селекция",
    category: "Десерти",
    description: "Комбинация от мини десерти и сладки за гости.",
    portions: "20 броя",
    priceFrom: 38,
    image: image("photo-1519869325930-281384150729"),
    tags: ["десерти", "подарък", "кафе"],
    active: true,
  },
];

export const demoOrders: CakeOrder[] = [
  {
    id: "ord-101",
    customerName: "Мария Георгиева",
    phone: "0888 234 112",
    cake: "Розов празник",
    occasion: "Рожден ден",
    date: "2026-05-22",
    portions: "12",
    flavor: "Ванилия",
    inscription: "Честит рожден ден, Ани!",
    receiveMethod: "Взимане от място",
    message: "Да бъде в нежни цветове.",
    status: "Нова",
    price: "от 52 лв.",
    internalNote: "Да се потвърди час за взимане.",
    createdAt: "2026-05-19T08:30:00.000Z",
  },
  {
    id: "ord-102",
    customerName: "Иван Петров",
    phone: "0897 510 440",
    cake: "Шоколадово злато",
    occasion: "Юбилей",
    date: "2026-05-20",
    portions: "14",
    flavor: "Шоколад",
    inscription: "60 години",
    receiveMethod: "Доставка",
    message: "Доставка след 17:00 в центъра.",
    status: "Потвърдена",
    price: "68 лв.",
    internalNote: "Куриерска доставка в рамките на града.",
    createdAt: "2026-05-18T13:15:00.000Z",
  },
  {
    id: "ord-103",
    customerName: "Елена Стоянова",
    phone: "0876 990 301",
    cake: "Торта по снимка",
    occasion: "Детско парти",
    date: "2026-05-24",
    portions: "16",
    flavor: "Ягода",
    inscription: "Мартин на 5",
    receiveMethod: "Взимане от място",
    message: "Има снимка за вдъхновение, ще я изпрати по Viber.",
    status: "Обадено",
    price: "Цена след уточнение",
    internalNote: "",
    createdAt: "2026-05-19T09:20:00.000Z",
  },
  {
    id: "ord-104",
    customerName: "Николай Димитров",
    phone: "0882 111 804",
    cake: "Класика с горски плодове",
    occasion: "Имен ден",
    date: "2026-05-19",
    portions: "10",
    flavor: "Плодова",
    inscription: "За здраве!",
    receiveMethod: "Взимане от място",
    message: "",
    status: "В процес",
    price: "48 лв.",
    internalNote: "Готова до 16:30.",
    createdAt: "2026-05-18T16:55:00.000Z",
  },
];

export const customers = [
  {
    name: "Мария Георгиева",
    phone: "0888 234 112",
    lastOrder: "Розов празник",
    orders: 3,
    note: "Предпочита по-леки кремове.",
  },
  {
    name: "Иван Петров",
    phone: "0897 510 440",
    lastOrder: "Шоколадово злато",
    orders: 2,
    note: "Често пита за доставка.",
  },
  {
    name: "Елена Стоянова",
    phone: "0876 990 301",
    lastOrder: "Торта по снимка",
    orders: 1,
    note: "Детски теми и ярки цветове.",
  },
];
